
- topic_name: /cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ
  qos:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 1

- topic_name: /camera/left/image_raw
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
  qos:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 1

- topic_name: /camera/right/image_raw
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
  qos:
    reliability: best_effort
    durability: volatile
    history: keep_last
    depth: 1